### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Metaln00b** [LeeHolmes/watchysim#4]
I am not able to load the solution, because of a missing file "WatchySim.vcxproj".
Is this an issue?
Can you tell us also, how to compile this project? - I cannot see any makefile

Thank you for sharing watchysim.

**Comment by LeeHolmes** [comment]
Ok, fixed and validated :) Try again.

To compile it from Visual Studio Community, use "F5" to Compile and Run, or "F6" to compile and run the exe separately.

**Comment by Metaln00b** [comment]
Thank you very much for the fast fix, works incredible good 🥇
